name: Atualizar o GitLab

on:
  push:
    branches:
      - develop  # Ou a branch que deseja sincronizar

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Enviar código para GitLab
        run: |
          git remote add gitlab https://oauth2:${{ secrets.personaltoken }}@github.com/09437736790/projetos.git
          git push gitlab develop
